// <auto-generated />
namespace PAdGWebAppMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Add2Models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add2Models));
        
        string IMigrationMetadata.Id
        {
            get { return "202410061720422_Add2Models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
